CREATE TABLE IF NOT EXISTS users (
  user_id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  name VARCHAR(255) NOT NULL,
  email VARCHAR(512) NOT NULL,

  CONSTRAINT pk_user PRIMARY KEY (user_id),
  CONSTRAINT UQ_USER_EMAIL UNIQUE (email)
);

CREATE TABLE IF NOT EXISTS item_requests (
  item_request_id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  description VARCHAR(255) NOT NULL,
  requester_id BIGINT NOT NULL,
  created_at TIMESTAMP WITHOUT TIME ZONE NOT NULL,

  CONSTRAINT pk_item_requests PRIMARY KEY (item_request_id),
  CONSTRAINT fk_request_requester FOREIGN KEY (requester_id) REFERENCES users (user_id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS items (
  item_id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  name VARCHAR(255) NOT NULL,
  description VARCHAR(512) NOT NULL,
  available BOOLEAN NOT NULL,
  owner_id BIGINT NOT NULL,
  item_request_id BIGINT,

  CONSTRAINT pk_item PRIMARY KEY (item_id),

  FOREIGN KEY (owner_id) REFERENCES users(user_id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS bookings (
  booking_id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  start_booking TIMESTAMP WITHOUT TIME ZONE NOT NULL,
  end_booking TIMESTAMP WITHOUT TIME ZONE NOT NULL,
  item_id BIGINT NOT NULL,
  booker_id BIGINT NOT NULL,
  status VARCHAR(255) NOT NULL,

  CONSTRAINT pk_booking PRIMARY KEY (booking_id),

  FOREIGN KEY (booker_id) REFERENCES users(user_id) ON DELETE CASCADE,
  FOREIGN KEY (item_id) REFERENCES items(item_id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS comments (
  comment_id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  text VARCHAR NOT NULL,
  item_id BIGINT NOT NULL,
  author_id BIGINT NOT NULL,
  created_at TIMESTAMP WITHOUT TIME ZONE NOT NULL,

  CONSTRAINT pk_comment PRIMARY KEY (comment_id),

  FOREIGN KEY (author_id) REFERENCES users(user_id) ON DELETE CASCADE,
  FOREIGN KEY (item_id) REFERENCES items(item_id) ON DELETE CASCADE
);

CREATE INDEX idx_item_owner ON items(owner_id);
CREATE INDEX idx_item_request ON items(item_request_id);
CREATE INDEX idx_request_requester ON item_requests(requester_id);
CREATE INDEX idx_booking_item ON bookings(item_id);
CREATE INDEX idx_booking_booker ON bookings(booker_id);
CREATE INDEX idx_comment_item ON comments(item_id);
CREATE INDEX idx_comment_author ON comments(author_id);


